apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-t71s
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-t71s
    app.kubernetes.io/part-of: tkwch-fix-0075-0064-app
  name: devfile-sample-t71s
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-t71s
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-t71s
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0-18-tenant/tkwch-fix-0075-0064-app/devfile-sample-t71s@sha256:cd197c8e0b62d1c402b90f3fa0036b2ce3e0a100928d0e0f88130c161f01f706
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
